# Generated by Django 5.1.1 on 2024-10-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
