# Generated by Django 5.1.1 on 2024-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_symptom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='malaria_type',
            field=models.CharField(choices=[('P. falciparum', 'Plasmodium falciparum'), ('P. vivax', 'Plasmodium vivax'), ('P. ovale', 'Plasmodium ovale'), ('P. malariae', 'Plasmodium malariae')], max_length=50),
        ),
    ]
